### ISSUE TITLE
turns while moving

### ISSUE THREAD

**Issue by huliqan** [fholger/crysis_vrmod#3]
How to delete awful backlash when turning the mouse ? 
during the turn, the weapon with hands moves first and only at the very end of the movement does the turn begin.
it's very uncomfortable :(((

**Comment by fholger** [comment]
That's by design so that you can aim your weapon in front of you without constantly rotating the whole view.

But you can turn it off, if you want to. Open the console (`~` button by default), then type `vr_yaw_deadzone_angle 0`.

**Comment by huliqan** [comment]
many thanks!!! You are the Best!!!

**Comment by HughVR** [comment]
[fholger](https://github.com/fholger)

And can you add vr_yaw_deadzone_angle 0 to the next mod release so that you don't have to enter it every time you start the game?) Thanks!

**Comment by fholger** [comment]
The setting should be persisted in your save games. I am not going to change the default, because it is intentional and the way I like it :)

**Comment by huliqan** [comment]
all works fine.Only one time need send it command in console and it saved forever!

**Comment by DravenWorks** [comment]
> But you can turn it off, if you want to. Open the console (`~` button by default), then type `vr_yaw_deadzone_angle 0`

any chance to lock the vertical pitch as well ? eg. vr_pitch_deadzone_angle 0

just want the Gamepad Analog Sticks to control the game the same as the non VR Mode.

Personally, i'm finding the controls in VR pretty unplayable for a game that requires quick target acquisition and despatch.

While i'm at it, the White Dot Reticle needs to be a different color like Red or Blue or something, because the White Dot disappears into the backgrounds pretty quick. eg. looking Cliffs or the Sand on a Beach.

It's worse when in Vehicles with Turrets .. the White Dot is so small it's pretty much Invisible.

Anyways, please don't take what i've said as criticism ... they are merely suggestions

The VR Mod is AWESOME !

**Comment by huliqan** [comment]
vr_pitch_deadzone_angle 0
it's too much! It is enough to lock  horizontal moving weapon (vr_yaw_deadzone_angle 0) 
But aiming with your head is pure perversion! :))) Play with keyboard + mouse .And that's all you need to be happy!)))

**Comment by DravenWorks** [comment]
> But aiming with your head is pure perversion! :))) Play with keyboard + mouse .And that's all you need to be happy!)))

The best solution is to have various control methods that give people the option to use or not.

Everyone has there own preference for VR Game controls ... playing with a VR Game with a Keyboard + Mouse is not an option i would ever choose.

**Comment by huliqan** [comment]
I'm sorry, I didn't mean to be rude, I'm just not very friendly with English
Sorry for being rude
